variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
}

variable "app_id" {
  description = "Name which identifies the deployed app"
  type        = string
}

variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
}

variable "cloudfront_domain_name" {
  description = "The  domain name for CloudFront distribution for CORS settings"
  type        = string
}

variable "api_backend_custom_domain_name" {
  description = "The Alternative domain name for API gateway"
  type        = string
}

variable "api_gateway_route53_zone_id" {
  type    = string
  default = "Z1U9ULNL0V5AJ3" # eu-central-1 fixed value : https://docs.aws.amazon.com/general/latest/gr/apigateway.html
}

variable "s3_ingestion_lambda_code_bucket" {
  type        = string
  description = "Optional S3 bucket for large ingestionLambda code"
}

variable "s3_ingestion_lambda_code_key" {
  type        = string
  description = "Optional S3 key for large ingestion Lambda code"
}

variable "s3_query_document_lambda_code_bucket" {
  type        = string
  description = "Optional S3 bucket for large query document Lambda code"
}

variable "s3_query_document_lambda_code_key" {
  type        = string
  description = "Optional S3 key for large query document Lambda code"
}

#-------------- File uploader variables -----------------------------------------------
# START
variable "api_file_upload_domain_name" {
  description = "The domain name for the API to get pre-signed file upload URLs"
  type        = string
}

variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate for the API Gateway"
  type        = string
}

variable "use_bucketav" {
  description = "Use BucketAV to prevent malware to be uploaded in S3 bucket"
  type        = bool
  default     = false
}

variable "enable_transfer_acceleration" {
  type        = bool
  description = "Enable S3 Transfer Acceleration?"
  default     = false
}

variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300
}

variable "lambda_memory_size_mb" {
  description = "Memory size in MB value for Lambda processing file which allow faster execution"
  type        = number
  default     = 512
}

variable "notification_email" {
  description = "Email address for notifications"
  type        = string
}

variable "route53_zone_name" {
  description = "Route53 zone name"
  type        = string
}

variable "bucket_av_sns_findings_topic_name" {
  description = "SNS topic name for bucket AV findings"
  type        = string
}
# END

#-------------- Bedrock and Chat variables -----------------------------------------------
# START
variable "embedding_model" {
  description = "Bedrock embedding model ID. Must stay consistent for the lifetime of the vector store — changing it requires dropping and recreating the document_chunks table and re-ingesting all documents."
  type        = string
  default     = "amazon.titan-embed-image-v1"
}

variable "min_relevance_score" {
  description = "Minimum cosine similarity score (0–1) for a chunk to be considered relevant. Chunks below this threshold are discarded before being sent to the LLM. Lower values return more results but risk sending irrelevant context."
  type        = number
  default     = 0.6
}

variable "embedding_dimensions" {
  description = "Output vector dimensions of the embedding model. Must match the model set in embedding_model: titan-embed-image-v1 = 1024, titan-embed-text-v1 = 1536, titan-embed-text-v2:0 = 1024."
  type        = number
  default     = 1024
}

variable "bedrock_model_inference_profile_arn" {
  description = "Bedrock model Inference profile arn"
  type        = string
}

variable "eval_model_arn" {
  description = "Bedrock model ID or ARN used as the LLM-as-judge in RAG evaluation. Should be a more capable model than the one used for answering to avoid self-evaluation bias."
  type        = string
  default     = "anthropic.claude-opus-4-5"
}

variable "bedrock_foundation_model_arns" {
  description = "List of Bedrock foundation model ARNs to allow invocation. Defaults to a wildcard that permits any model in any region, enabling LLM portability. Restrict to specific ARNs in production for least-privilege."
  type        = list(string)
  default     = ["arn:aws:bedrock:*::foundation-model/*"]
}

variable "max_search_results" {
  description = "Maximum number of document chunks to retrieve for context"
  type        = number
  default     = 5
}

variable "llm_temperature" {
  type    = number
  default = 0.7
}

variable "llm_max_tokens" {
  description = "It sets the maximum length of Claude's response"
  type        = number
  default     = 2000
}
# END

#-------------- RDS variables -----------------------------------------------
variable "availability_zones" {
  description = "Two AZs for RDS subnet group and Lambda subnets"
  type        = list(string)
  default     = ["eu-central-1a", "eu-central-1b"]
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t4g.micro"
}